import type { Person } from "@/lib/types";

// Demo people so the product runs end-to-end with ZERO external config.
// Replace by pointing the Supabase adapter at a real `profiles` table.
export const SEED_PEOPLE: Person[] = [
  {
    id: "seed-1",
    name: "Aarav Sharma",
    headline: "Staff AI Engineer · LLM infra & agents",
    current_title: "Staff AI Engineer",
    company: "Nutanix",
    location: "Bengaluru, India",
    summary: "Builds LLM serving infra and agent frameworks at scale.",
    experience: [
      { company: "Nutanix", title: "Staff AI Engineer", start: "2022" },
      { company: "Flipkart", title: "Senior ML Engineer", start: "2018", end: "2022" },
    ],
    skills: ["LLMs", "Python", "Agents", "Kubernetes", "Inference", "RAG"],
    education: [{ school: "IIT Bombay", degree: "B.Tech CS" }],
    social_links: [{ type: "linkedin", url: "https://linkedin.com/in/example-aarav" }],
    profile_strength: 88,
    confidence_score: 92,
    last_updated: "2026-05-01",
    _sources: [{ adapter: "seed", raw_id: "1", trust: 1 }],
  },
  {
    id: "seed-2",
    name: "Priya Nair",
    headline: "Senior Applied AI Engineer · NLP",
    current_title: "Senior Applied AI Engineer",
    company: "Razorpay",
    location: "Bengaluru, India",
    summary: "Ships applied NLP and fraud models in production fintech.",
    experience: [
      { company: "Razorpay", title: "Senior Applied AI Engineer", start: "2021" },
      { company: "Freshworks", title: "ML Engineer", start: "2018", end: "2021" },
    ],
    skills: ["NLP", "Python", "PyTorch", "Applied AI", "MLOps"],
    education: [{ school: "NIT Trichy", degree: "B.Tech" }],
    social_links: [{ type: "github", url: "https://github.com/example-priya" }],
    profile_strength: 81,
    confidence_score: 87,
    last_updated: "2026-04-12",
    _sources: [{ adapter: "seed", raw_id: "2", trust: 1 }],
  },
  {
    id: "seed-3",
    name: "Rohan Mehta",
    headline: "ML Platform Engineer · agent builder",
    current_title: "ML Platform Engineer",
    company: "Postman",
    location: "Bengaluru, India",
    summary: "Owns the internal ML platform and agent tooling.",
    experience: [
      { company: "Postman", title: "ML Platform Engineer", start: "2020" },
      { company: "Ola", title: "Backend Engineer", start: "2017", end: "2020" },
    ],
    skills: ["ML Platform", "Agents", "Go", "Python", "LLMs", "Infra"],
    education: [{ school: "BITS Pilani", degree: "B.E." }],
    social_links: [{ type: "linkedin", url: "https://linkedin.com/in/example-rohan" }],
    profile_strength: 79,
    confidence_score: 85,
    last_updated: "2026-03-22",
    _sources: [{ adapter: "seed", raw_id: "3", trust: 1 }],
  },
  {
    id: "seed-4",
    name: "Sara Khan",
    headline: "AI Research Engineer · research-to-product",
    current_title: "AI Research Engineer",
    company: "Sarvam AI",
    location: "Bengaluru, India",
    summary: "Bridges research and product for Indic LLMs.",
    experience: [
      { company: "Sarvam AI", title: "AI Research Engineer", start: "2023" },
      { company: "Microsoft Research", title: "Research SDE", start: "2020", end: "2023" },
    ],
    skills: ["LLMs", "Research", "Python", "Fine-tuning", "Evaluation"],
    education: [{ school: "IISc Bangalore", degree: "M.Tech" }],
    social_links: [{ type: "twitter", url: "https://twitter.com/example-sara" }],
    profile_strength: 84,
    confidence_score: 83,
    last_updated: "2026-05-19",
    _sources: [{ adapter: "seed", raw_id: "4", trust: 1 }],
  },
  {
    id: "seed-5",
    name: "Daniel Okoro",
    headline: "Senior Backend Engineer · distributed systems",
    current_title: "Senior Backend Engineer",
    company: "Stripe",
    location: "Remote (Lagos, Nigeria)",
    summary: "Scales payment infra; some ML adjacency, not core AI.",
    experience: [
      { company: "Stripe", title: "Senior Backend Engineer", start: "2021" },
      { company: "Andela", title: "Software Engineer", start: "2018", end: "2021" },
    ],
    skills: ["Go", "Distributed Systems", "Kafka", "Postgres"],
    education: [{ school: "University of Lagos", degree: "B.Sc" }],
    social_links: [{ type: "github", url: "https://github.com/example-daniel" }],
    profile_strength: 74,
    confidence_score: 80,
    last_updated: "2026-02-08",
    _sources: [{ adapter: "seed", raw_id: "5", trust: 1 }],
  },
  {
    id: "seed-6",
    name: "Meera Iyer",
    headline: "VP Engineering · scaled B2B SaaS 0→1",
    current_title: "VP Engineering",
    company: "Chargebee",
    location: "Chennai, India",
    summary: "Built and scaled engineering orgs at B2B SaaS startups.",
    experience: [
      { company: "Chargebee", title: "VP Engineering", start: "2019" },
      { company: "Zoho", title: "Engineering Manager", start: "2014", end: "2019" },
    ],
    skills: ["Leadership", "B2B SaaS", "Scaling", "Architecture"],
    education: [{ school: "Anna University", degree: "B.E." }],
    social_links: [{ type: "linkedin", url: "https://linkedin.com/in/example-meera" }],
    profile_strength: 86,
    confidence_score: 90,
    last_updated: "2026-04-30",
    _sources: [{ adapter: "seed", raw_id: "6", trust: 1 }],
  },
  {
    id: "seed-7",
    name: "James Park",
    headline: "Founder & CTO · AI agents startup",
    current_title: "Co-founder & CTO",
    company: "Stealth",
    location: "San Francisco, USA",
    summary: "Founder building autonomous agents for ops teams.",
    experience: [
      { company: "Stealth", title: "Co-founder & CTO", start: "2024" },
      { company: "Scale AI", title: "Tech Lead", start: "2020", end: "2024" },
    ],
    skills: ["Agents", "LLMs", "Founder", "Python", "Product"],
    education: [{ school: "Stanford", degree: "B.S. CS" }],
    social_links: [{ type: "twitter", url: "https://twitter.com/example-james" }],
    profile_strength: 77,
    confidence_score: 78,
    last_updated: "2026-06-01",
    _sources: [{ adapter: "seed", raw_id: "7", trust: 1 }],
  },
  {
    id: "seed-8",
    name: "Ananya Gupta",
    headline: "Senior AI Engineer · agent infrastructure",
    current_title: "Senior AI Engineer",
    company: "Zomato",
    location: "Gurugram, India",
    summary: "Builds agentic workflows and LLM eval pipelines.",
    experience: [
      { company: "Zomato", title: "Senior AI Engineer", start: "2022" },
      { company: "Paytm", title: "Data Scientist", start: "2019", end: "2022" },
    ],
    skills: ["Agents", "LLMs", "Python", "Evaluation", "RAG", "Infra"],
    education: [{ school: "DTU", degree: "B.Tech" }],
    social_links: [{ type: "linkedin", url: "https://linkedin.com/in/example-ananya" }],
    profile_strength: 82,
    confidence_score: 86,
    last_updated: "2026-05-25",
    _sources: [{ adapter: "seed", raw_id: "8", trust: 1 }],
  },
];
